os: linux

dist: bionic

language: python

Python:
  - "3.7"

before_install:
  # require for installing pyodbc
  - sudo apt-get install unixodbc-dev

# command to setup datamegh
install:
  - make setup

# check for black format
# build will stop if check fail 
before_script:
  - black --check --diff . 

script:
  - make test

before_deploy:
  # require for git versioning
  - sudo curl https://raw.githubusercontent.com/fsaintjacques/semver-tool/2.1.0/src/semver -o /usr/local/bin/semver && sudo chmod +x /usr/local/bin/semver
  - semver --version
  # Create a tag prior to release
  - make tag
 
# Make a release to github 
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  prerelease: true 
  skip_cleanup: true
  on:
    branch: master

