install:
  - sudo curl https://raw.githubusercontent.com/fsaintjacques/semver-tool/2.1.0/src/semver -o /usr/local/bin/semver && sudo chmod +x /usr/local/bin/semver
  - semver --version
script:
  - make test

before_deploy:
  # require for git versioning
  # Create a tag prior to release
  - sudo snap install hub --classic
 
# Make a release to github 
deploy:
  provider: script
  skip_cleanup: true
  script: make release
  on:
    branch:
    - master
    - release-maker

